services:
  ctfd:
    build: .
    user: root
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .data/CTFd/logs:/var/log/CTFd
      - .data/CTFd/uploads:/var/uploads
      - .:/opt/CTFd:ro
    networks:
        default:
        internal:

  nginx:
    image: nginx:stable
    restart: always
    volumes:
      - ./conf/nginx/http.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - ctfd

  mysql-judge:
    image: mysql:8.0.43
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=ctfd_sql_judge_password
      - MYSQL_DATABASE=ctfd_sql
    volumes:
      - .data/mysql-judge:/var/lib/mysql
    networks:
      - internal
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --max-connections=5000]


  sql-judge:
    build: ./CTFd/plugins/sql_challenges
    restart: always
    networks:
      - internal
    env_file:
      - .env
    volumes:
      - .data/CTFd/logs:/var/log/CTFd
    depends_on:
      - mysql-judge

networks:
    default:
    internal:
        internal: true
