#!/usr/bin/env python3
import argparse
import json

from release_registry import AwsClient, AwsConfig, ReleaseRegistry, ReleaseRegistryError


def main() -> None:
    parser = argparse.ArgumentParser(description="Retire a SQL Playzone release channel")
    parser.add_argument("--channel", required=True, choices=("dev", "main"))
    parser.add_argument("--apply", action="store_true")
    parser.add_argument("--artifact-prefix", default="sql-2026-s2")
    parser.add_argument("--profile", default="hyu-ddps")
    parser.add_argument("--region", default="ap-northeast-2")
    arguments = parser.parse_args()
    registry = ReleaseRegistry(
        AwsClient(AwsConfig(arguments.profile, arguments.region)),
        f"/sql-playzone/{arguments.artifact_prefix}",
    )
    paths = registry.retire_channel(arguments.channel, apply=arguments.apply)
    print(json.dumps({"applied": arguments.apply, "parameters": paths}, indent=2))


if __name__ == "__main__":
    try:
        main()
    except ReleaseRegistryError as error:
        raise SystemExit(str(error)) from error
